import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ul>
            <li>
                <Link href="/home">home</Link>
            </li>
            <li>
                <Link href="/login">login</Link>
            </li>
          </ul> 
        </div>
        
        {children}</body>
    </html>
  )
}
